travis:
  secure:
    BINSTAR_TOKEN: RBv+Se1B3x7M1LyxMP2q+uVZQ36EsG7wnx6xAIw9tG3nswAQ6jBRwUQQBQVn7wRJ1gXXtPcTxh1A42EpXOdj5S1npg9+kmWvFLy3i41IgN5bBRJC3Vjp/9s+9gL8079WkSYkJwCbLnb1EJGjIJABpx0rmcDRfanaD0YxXEH8LZILYbkeo5/uDMLJ87Pb3qUG/+7O1oLOpWvJ6gPSt+pLRvQq499DYekc+4zlEV9KxPXsUIvv5D7TTI1naN9n49hxI0vuMcNRxszuEUXmX2VOccT8xH0LcEgfcbUww70x7hV68tmo4hHaFx7JaMe9GtSkPF+lyBc6DtIZVZ8e3idnkHd+HnEYygy6N3LcjD+Iw2RovMYuPIQ8g4ZrIpnEhtYnLxicN/DLYeIucqGcxP9cDIgOOVojZqmrOkCDJb3NhNV/0yjVgMG3Ox8AqJ4S4PDLWf3l5EFAH8VQOOkufz+5wV8eU6kOvKMkpXLR+u5RmcokxYIGsO+3Qdy0HCN8JNrERHCdOeAwjLZO35kD/mMULG3lW79g2xLOFirfQp7EE63FujgwrsAAyI98R2h0+zU2nfzmRHYBRPLKdVph5IhIWr9ivfArEAZvzzpkIf0VUppJwLxsTDRastI3XujWVVqDw8u0acmA3CgT7O+V4eaJ+Yy2MBIk9PtbAS+cDkjXC+0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
